name: Assign PR to SantaClaus
on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Assign to SantaClaus
        run: gh pr edit ${{ github.event.number }} --add-reviewer SantaClaus --add-assignee @me
        env:
          GH_TOKEN: ${{ github.token }}