name: Assign PR to SantaClaus
on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign to SantaClaus
        run: gh pr edit ${{ github.event.number }} --add-reviewer @me --add-assignee @me --body "Assign to SantaClaus"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}